ktor:
  application:
    modules:
      - ApplicationKt.module
  deployment:
    host: localhost
    port: 8080

jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"

database:
  url: "jdbc:postgresql://localhost:5432/postgres"
  driver: "org.postgresql.Driver"
  user: "postgres"
  password: "postgres"

ai:
    lmstudio:
        url: "http://localhost:1234"
        apiKey: "lm-studio"
        model: "openai/gpt-oss-20b"
    systemPrompt: "You are a helpful assistant."